- name: Install and run nginx
  hosts: web
  become: yes # for root access
  tasks:
  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state : present   # if you install the nginx then state is present
