- name: play level variables
  hosts: local 
  connection: local 
  vars:
  - course.yml 
  tasks:
  - name: print variables
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "course is {{COURSE}}, trainer is {{TRAINER}}" 