- name: variables Preference 
  hosts: local 
  connection: local
  vars: 
    Name: "Ansible from Play"
  # vars_files:
  #  - course.yml
  vars_prompt:
   - name: Name
     prompt: Enter your Name
     private: false
  tasks:
  - name: print name 
    # vars:
    #   NAME: "Ansible from task"
    ansible.builtin.debug:
      msg: "Hi {{NAME}}"
  
